name: AcreetionOS Changelog & Social Blast

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last commit
        run: git log -1 --pretty=%B > commit.txt

      - name: Rewrite commit for public
        run: |
          COMMIT=$(jq -R -s '.' commit.txt)
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\": \"Rewrite this commit so it’s exciting and easy for non-developers: $COMMIT\"}" \
            https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1)

          PRETTY=$(echo "$RESPONSE" | jq -r '
            if type == "array" and .[0].generated_text then
              .[0].generated_text
            elif type == "object" and .generated_text then
              .generated_text
            elif type == "object" and .error then
              empty
            else
              empty
            end
          ')

          if [ -z "$PRETTY" ]; then
            echo "AI rewrite failed, skipping Mastodon and changelog update."
            echo "" > pretty_commit.txt
            echo "SKIP" > skip.txt
          else
            echo "$PRETTY" > pretty_commit.txt
          fi

      - name: Update changelog.html
        if: ${{ !hashFiles('skip.txt') }}
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          ENTRY="<p><strong>$DATE:</strong> $(cat pretty_commit.txt | sed 's/"/\&quot;/g')</p>"
          echo "$ENTRY" >> changelog.html
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add changelog.html
          git commit -m "Update changelog"
          git push

      - name: Post to Mastodon
        if: ${{ !hashFiles('skip.txt') }}
        run: |
          STATUS=$(cat pretty_commit.txt)
          curl -X POST "https://fosstodon.org/api/v1/statuses" \
            -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
            -F "status=$STATUS"
